f = open('routine', 'r')
lines = f.readlines()
print(len(lines))
#
# f = open('vgaText_top.vhd', 'r')
# lines = f.readlines()
# lines[107] = "		textPassageLength => %s\n" % (len(question))
# lines[112] = '		textPassage => "%s",\n' % (question)
# lines[114] = '		colorMap => (%s downto 0 => "111" & "111" & "11"),\n' % (len(question) - 1)
# lines[124] = "		textPassageLength => %s\n" % (len(answer) + 7)
# lines[129] = '		textPassage => "ANSWER:%s",\n' % (answer)
# lines[131] = '		colorMap => (%s downto 0 => "111" & "111" & "11"),\n' % (len(answer) + 6)
# f.close()
# f = open('vgaText_top.vhd', 'w')
# f.writelines(lines)
# f.close()
